# Generated by Django 3.2.8 on 2021-10-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('SellDateTime', models.DateTimeField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.product', verbose_name='کالا')),
            ],
        ),
    ]
